### ISSUE TITLE
my-profile-dialog.component.html: Default to general tab when opening the page 

### ISSUE THREAD

**Issue by shambhavi2001** [decisiontft/decisiontft.github.io#2]
On opening the link to the shadow site, the user sees a blank page with only an options panel: 
![image](https://user-images.githubusercontent.com/52174911/184506048-ab4083a7-9b3b-480b-a6e7-3ea603aea340.png)

We should attempt to make the general tab as the default on opening the webpage, as it is right now on the Optevo platform when you click on the my profile tab. Like this: 
![image](https://user-images.githubusercontent.com/52174911/184506085-09697cc3-4458-4e22-b628-555b3b8b830a.png)

**Comment by decisiontft** [comment]
General Tab has been set as default tab.
